# Build
FROM node:20.3.0-alpine3.18 AS builder
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
ENV NODE_OPTIONS=--openssl-legacy-provider
RUN npm run build

# Prod
FROM docker.io/library/nginx:latest
# RUN addgroup app && adduser -G app -S app
# USER app
# RUN mkdir /app && chown app:app /app
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 4000

