FROM node:20.3.0-alpine3.18

RUN addgroup app && adduser -G app -S app
RUN mkdir /app && chown app:app /app
USER app

WORKDIR /app
COPY --chown=app:app package*.json .
RUN npm install
COPY --chown=app:app . .

# ENV PORT=4000
# ENV REACT_APP_API_CALL=http://localhost:4001
# ENV NODE_OPTIONS=--openssl-legacy-provider

EXPOSE 4000
CMD ["npm", "start"]