versions: "3.8"
services:

  store-web:
    build: ./store-web
    ports:
      - '4000:4000'
    volumes:
      - ./store-web:/app
      - /app/node_modules

  store-api:
    build: ./store-api
    ports:
      - '4001:4001'
    volumes:
      - ./store-api:/app
      - /app/node_modules

  store-db:
    privileged: true
    build: ./store-db
    restart: always
    ports:
      - '5432:5432'
    volumes:
    # here we create and link persistant postgres database, so if image is deleted the data is not lost
      - db:/var/lib/postgresql/data
    # here we create our initial tables
      - ./store-db/store.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  db:
    driver: local
